name: Crates
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          no-verify: true # try to ignore "dependency `ic-crypto-standalone-sig-verifier` does not specify a version"
          ignore-unpublished-changes: true
