name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build canisters
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install ic-wasm
        mkdir out
        cargo build --target wasm32-unknown-unknown --release --locked -p ic_tee_identity
        for CAN in ic_tee_identity
        do
          cp "target/wasm32-unknown-unknown/release/$CAN.wasm" out/
          cp "src/$CAN/$CAN.did" "out/$CAN.did"
          WASM="out/$CAN.wasm"
          ic-wasm $WASM -o $WASM metadata candid:service -f "out/$CAN.did" -v public
          ic-wasm $WASM -o $WASM shrink
          ic-wasm $WASM -o $WASM optimize O3 --inline-functions-with-loops
          gzip $WASM
          SHA256="$(sha256sum < "out/$CAN.wasm.gz" | sed 's/ .*$//g')"
          echo $SHA256 > "out/$CAN.wasm.gz.$SHA256.txt"
        done
        ls -lah out
    - name: Build linux binary
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
        for PACK in ic_tee_nitro_gateway ic_tee_host_daemon ic_tee_daemon
        do
          cargo build --release --locked -p $PACK --target x86_64-unknown-linux-musl
          cp "target/x86_64-unknown-linux-musl/release/$PACK" "out/"
          SHA256="$(sha256sum < "out/$PACK" | sed 's/ .*$//g')"
          echo $SHA256 > "out/$PACK.$SHA256.txt"
        done
        ls -lah out
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/*
